### ISSUE TITLE
Change the frontend color schema

### ISSUE THREAD

**Issue by zeppaman** [arduosoft/RawCMS#184]
**Describe the bug**
The project is based on default theme of veautify. It is shocking blue. We would change it to the indigo dark scheme, soberer.

** References **
https://vuetifyjs.com/it-IT/styles/colors

**Comment by abimael-o-o** [comment]
Hi, I'm a first timer. Is it possible for me to take this ?

**Comment by zeppaman** [comment]
Hi @abimael-o-o sure you can. This is a coding task so it requires setup on you local env. The contribution file should contain all you need to start. Ui is made in vuejs and pure javascript.  backend api are in asp.net core, but for this task you do not have to change anything on that side.
I suggest to join the Gitter channel and ask for an help on the initial setup. 

A great roadmap could be:
- [ ] set up your local env, asking help on gitter if you lost more than 1 hour (setup  normally need 10 miuntes)
- [ ] in case you will find some suggestion to the contribution.md file, please feel free to update adn PR it
- [ ] do the dirty job
- [ ] upload a screen attached to this task, so that we could see if it is as expected.

What do you think about it?
@keggyy

**Comment by keggyy** [comment]
HI @abimael-o-o, for me the road map described from @zeppaman is the right approach for this task. If you have any question about setup local environment write on [Gitter](https://gitter.im/arduosoft/RawCMS-Headless-CMS-Aspnet)

**Comment by abimael-o-o** [comment]
Something like this ?

![image](https://user-images.githubusercontent.com/53713385/74192928-798c6880-4c24-11ea-93f2-3528166c1f8c.png)
![image](https://user-images.githubusercontent.com/53713385/74192808-41852580-4c24-11ea-9a78-c1c565c299ce.png)

**Comment by keggyy** [comment]
Hi @abimael-o-o, better than before. I like something like teal (but I don't have a great taste on CSS :-)), @zeppaman, do you have some color preferences?

**Comment by zeppaman** [comment]
@abimael-o-o great job! A lot better than blue shocking. I will stay on blue tones, as it is a tech product. I will try also indigo darken 4 or blue darken 4. @abimael-o-o what is your personal preference?

**Comment by zeppaman** [comment]
@keggyy @abimael-o-o  any feedback on this?

**Comment by abimael-o-o** [comment]
@zeppaman Yeah I like the indigo darken4

**Comment by zeppaman** [comment]
@abimael-o-o well, @keggyy  didn't reply, but we are 2/3 in favor of indigo darken 4, so we can proceed with indigo darken 4 ;-) could you change, commit, push and open a new PR? I will approve it shortly.
