### ISSUE TITLE
Review readme.md

### ISSUE THREAD

**Issue by zeppaman** [arduosoft/RawCMS#186]
Review the document to fix spelling errors, grammar mistakes.

**Comment by alti21** [comment]
Hi, can I work on this issue?

**Comment by keggyy** [comment]
Hi @alti21, sure you can work this task

**Comment by zeppaman** [comment]
Hi @alti21  thank you for this contribution. the changes are already merged. Let me know if you like to contribute in another way (like testing, coding, etc..). As you see we are open to all proposals. Of course, if you like this project, I suggest adding a star, join the Gitter channel and test it!
