### ISSUE TITLE
Change the log path

### ISSUE THREAD

**Issue by zeppaman** [arduosoft/RawCMS#204]
in file https://github.com/arduosoft/RawCMS/blob/master/RawCMS/conf/NLog.Development.config there is a wron path.

The configuration uses NLog settings.

**What is expected**
The log are written on the main repo folder, at root level. The log folder will be "log". No changes are required on all other log files. The folder must be created if not present( createDir attribute on settings). The folder is marked as ignored on .gitignore
```xml
<target xsi:type="File" name="allfile" fileName="/var/rawcms/nlog-all-${shortdate}.log"
                layout="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|${message}  ${exception:format=ToString,StackTrace}" />


```
https://github.com/nlog/NLog/wiki/File-target

**Steps**
1. Fork the project
2. Start a new branch from develop
3: Implement changes
4. Make a pull request to the original development branch

** key points **
-  change the log
- the log must be written on log folder inside the main repo folder
- log folder must be ignored in git

**Comment by ranganayakee** [comment]
@zeppaman  Can I take this up? I have the following questions - 

1.Does the path of internalLogFile be changed too?
2. Should the log folder be present at the same level as highlighted below - 
![image](https://user-images.githubusercontent.com/2928031/75847514-ae5f8b80-5d9c-11ea-9c3b-8c7857fdb821.png)

**Comment by zeppaman** [comment]
1. Yes. always inside the log folder
2. Yes, the folder has to be git-ignored.

**Comment by zeppaman** [comment]
hi @ranganayakee, can I assign it to you?
