### ISSUE TITLE
Review readme.md

### ISSUE THREAD

**Issue by zeppaman** [arduosoft/RawCMS#208]
Review the document to fix spelling errors, grammar mistakes.
New document https://github.com/arduosoft/RawCMS/blob/master/docs/Tutorial.md have to be checked too.

**Comment by NehaMadnani** [comment]
I would like to take this up.

**Comment by zeppaman** [comment]
Hi, @NehaMadnani nice to meet you. You can fork the repo, apply all changes and then make a PR form your master branch to our. Please ask for integration if some information is missed inside the files.

**Comment by ranganayakee** [comment]
Is this still available?

**Comment by zeppaman** [comment]
Sorry, this task was completed (Thanks again to @nel417  for this contribution)!
