### ISSUE TITLE
Allow Lambdas to interact with internal data

### ISSUE THREAD

**Issue by keggyy** [arduosoft/RawCMS#209]
For the moment is not possible to interact with internal data using Lambdas, now you should call rawcms API for change internal data.
On [LambdaController](https://github.com/arduosoft/RawCMS/blob/develop/Plugins/RawCMS.Plugins.Core/Controllers/JsLambdaController.cs) register instance of CRUDService on jint Engine (something like JavascriptRestClient), this allowing users to interact with data without call API.
The name of this class in javascript code should be "RAWCMSCrudService".
For register C# class instance on jint view [this](https://github.com/sebastienros/jint/issues/224). 

## Acceptance criteria

On documentation add an example of Lambda that works on internal data using RAWCMSCrudService.

**Comment by zeppaman** [comment]
A small trick on this. Atm there is two places where the js engine is used.

The place where do the change is
https://github.com/arduosoft/RawCMS/blob/develop/RawCMS.Library/Lambdas/JsDispatcher.cs
and
https://github.com/arduosoft/RawCMS/blob/develop/Plugins/RawCMS.Plugins.Core/Controllers/JsLambdaController.cs

As further step, after this task, we will refactor to use only one piece of code

**Comment by tokarzkj** [comment]
Thanks for the direction. I don't have much to show yet, but I am working on it.
