### ISSUE TITLE
Grammar and spelling fixes in /docs/CONTRIBUTING.md

### ISSUE THREAD

**Issue by MikeHigginbottom** [arduosoft/RawCMS#211]
There are a number of grammatical and spelling errors in /docs/CONTRIBUTING.md

**Comment by MikeHigginbottom** [comment]
Mmm. First time contributing to a project and I'm not sure of the process. Does someone need to approve this as an issue and assign it to me? I'll clone the repo and get started in the meantime.

**Comment by zeppaman** [comment]
Hi @MikeHigginbottom you can take this task! For assigning It I need to add you to the project, it's a GitHub requirement...I'm going to do it. In the meanwhile, you can fork the project, start working on the task and make a PR when ready.

**Comment by zeppaman** [comment]
Hi @MikeHigginbottom  thank you again for this contribution! PR is already merged,  I'm closing the task.
