### ISSUE TITLE
Rename property

### ISSUE THREAD

**Issue by zeppaman** [arduosoft/RawCMS#215]
In file https://github.com/arduosoft/RawCMS/blob/develop/Plugins/RawCMS.Plugins.Core/AuthPlugin.cs

The property  
  public List<ExternalProvider> ExternalProvider { get; set; } = new List<ExternalProvider>();

Must be renamed to

 ExternalProviderS because thi is a list.

This will need to rename it across other files.

Also section in https://github.com/arduosoft/RawCMS/blob/develop/docs/Authentication.md must be changed.

**Comment by Dansr81** [comment]
I can start with this issue

**Comment by zeppaman** [comment]
Thank you @Dansr81 , pr accepted.
