### ISSUE TITLE
Refactoring on fileAuthConfig

### ISSUE THREAD

**Issue by zeppaman** [arduosoft/RawCMS#216]
The file contains too many classes. Each class must be moved to a single file. Other code parts must be changed accordingly.

https://github.com/arduosoft/RawCMS/blob/develop/Plugins/RawCMS.Plugins.Core/Configuration/AuthConfig.cs

**Comment by Dansr81** [comment]
@zeppaman 
You use a specific namespace and file naming convention? 
Can i create the new class files `AuthConfig.[ClassName].cs` and put all under the namespace `RawCMS.Plugins.Core.Configuration.AuthConfig` ?

**Comment by zeppaman** [comment]
All classes can be at the same level on RawCMS/Plugins/RawCMS.Plugins.Core/Configuration/ and so in the same namespace  `RawCMS.Plugins.Core.Configuration`

**Comment by zeppaman** [comment]
@Dansr81 on the PR please use develop branch as the destination for the PR

**Comment by zeppaman** [comment]
@Dansr81  great contribution! your changes were merged and now in production!
