### ISSUE TITLE
Review doc of Authentication.md

### ISSUE THREAD

**Issue by zeppaman** [arduosoft/RawCMS#220]
The file https://github.com/arduosoft/RawCMS/blob/master/docs/Authentication.md needs to be reviewed.

Step for completing the task:
1) Fork the repo
2) change the file
3) submit a PR

**Comment by ranganayakee** [comment]
@zeppaman - I can pick this up.

**Comment by imanishbarnwal** [comment]
Hello, @zeppaman. I am up for this. Can I do it?

**Comment by zeppaman** [comment]
Sure!

**Comment by imanishbarnwal** [comment]
Hello, @zeppaman I just send a [PR](https://github.com/arduosoft/RawCMS/pull/259) request can you check that. And let me know if any issues exist there. Thank you!!

**Comment by zeppaman** [comment]
Thank you for contributing.
