### ISSUE TITLE
Refactoring for RawUserStore

### ISSUE THREAD

**Issue by zeppaman** [arduosoft/RawCMS#227]
## User story
The file contains too many classes.
https://github.com/arduosoft/RawCMS/blob/master/Plugins/RawCMS.Plugins.Core/Stores/RawUserStore.cs

## task
Split the file in one class per file in the same folder and namespace.

## acceptance criteria
The program compiles and you can log in on your local

**Comment by TimurMirzaiev** [comment]
I would take it
