### ISSUE TITLE
Review Readme.md file and fix typos

### ISSUE THREAD

**Issue by zeppaman** [arduosoft/RawCMS#251]
The file Readme.md was updated and need to be reviewed.

Please:
1. Fork the repository
2. Make fixes
3. Submit a PR

https://github.com/arduosoft/RawCMS/edit/master/README.md

**Comment by Zindra** [comment]
Hello zeppaman , i can take ticket.

**Comment by zeppaman** [comment]
You are welcome. Assigned to you.

**Comment by zeppaman** [comment]
Hi @Zindra, are you working on it or we can reassign?

**Comment by Kayla312** [comment]
@zeppaman If there is no response in the next couple of days, mind if I take point on the minor fixes?

**Comment by zeppaman** [comment]
@Kayla312 yes, you can work on this task. just fork, fix and then open a PR.
