### ISSUE TITLE
Review documentation page for background jobs

### ISSUE THREAD

**Issue by zeppaman** [arduosoft/RawCMS#254]
The page need to be doublechecked fo typos or errors.
https://github.com/arduosoft/RawCMS/blob/features/merge-ui-fx/docs/BackgroundJobs.md

**Comment by imanishbarnwal** [comment]
Hello, @zeppaman I glad to take this issue. Can I do this?

**Comment by zeppaman** [comment]
@imanishbarnwal sure! just fork and open a PR when ready ! the pr must be done on same branch (not on master).

**Comment by imanishbarnwal** [comment]
Yeah for sure. Thanks @zeppaman 

> @imanishbarnwal sure! just fork and open a PR when ready ! the pr must be done on same branch (not on master).

**Comment by imanishbarnwal** [comment]
Hello, @zeppaman just created a fresh [PR](https://github.com/arduosoft/RawCMS/pull/258) please check that and let me know. Thank you!!

**Comment by zeppaman** [comment]
@imanishbarnwal  thank you for what you have done. The only thing to fix, before accepting PR it to solve the conflict on your brand (if you enter the PR page you should see a button to complete this part). Thank you again!

**Comment by imanishbarnwal** [comment]
> @imanishbarnwal thank you for what you have done. The only thing to fix, before accepting PR it to solve the conflict on your brand (if you enter the PR page you should see a button to complete this part). Thank you again!

![image](https://user-images.githubusercontent.com/46371923/81780432-26bc9880-9514-11ea-8145-9b10fa76ed2e.png)
But in this [PR](https://github.com/arduosoft/RawCMS/pull/258) I am not getting any conflicts can you please tell me where I am going wrong. Thank You!

**Comment by zeppaman** [comment]
You are right. I was picking the wrong PR, sorry for my wrong request. PR approved and merged. Thank you!

**Comment by imanishbarnwal** [comment]
> You are right. I was picking the wrong PR, sorry for my wrong request. PR approved and merged. Thank you!

Thank you very much 😄
