### ISSUE TITLE
Update C# Language version

### ISSUE THREAD

**Issue by AaqibAhamed** [arduosoft/RawCMS#270]
The latest C# compiler determines a default language version based on your project's target framework or frameworks. This is because the C# language may have features that rely on types or runtime components that are not available in every .NET implementation. This also ensures that for whatever target your project is built against, you get the highest compatible language version by default.

Following issues arise when building solution .

>  Feature 'using declarations' is not available in C# 7.3. Please use language version 8.0 or greater 

Reference - https://stackoverflow.com/questions/58624146/feature-using-declarations-is-not-available-in-c-sharp-7-3-please-use-languag

**Comment by AaqibAhamed** [comment]
Closed with PR #271

**Comment by zeppaman** [comment]
Thank you @AaqibAhamed  for your contribution!
