### ISSUE TITLE
Case Username

### ISSUE THREAD

**Issue by keggyy** [arduosoft/RawCMS#32]
Username is case sensitive and work only if is write on upper case.

In  _users collection i have:

`{"_id":"5c716e09efb5283144ec154a","UserName":"ema","NormalizedUserName":"ema","Email":"emanuele.bucarelli@gmail.com","NormalizedEmail":"emanuele.bucarelli@gmail.com","Roles":[],"Metadata":{},"_createdon":"2018-12-23T17:43:50.2602188+01:00","_modifiedon":"2018-12-23T17:43:50.266117+01:00","PasswordHash":"WFla"}`

and I unable to get token, if change NormalizedUserName in upper case all work

**Comment by zeppaman** [comment]
the missing part:
- [ ] change encription from base64 to sha
- [ ] add lambda to manage password computation (only admin can change it atm, as user is into _user collection) or add an embedded lambda endpoint
- [ ] normalize username on both direction (write+read)

**Comment by zeppaman** [comment]
Implemented using presave and post save lambda. 
Due to actual framework limitation,uniqueness check on username is not implemented. This will require to support contrasaints on schema
