### ISSUE TITLE
Internal Server Error on crud service if Authorization in header

### ISSUE THREAD

**Issue by girardengo** [arduosoft/RawCMS#52]
**Issue**
Internal server error  when crud service are called with Authorization in header

**To Reproduce**

using client (after logging in ):
 
`dotnet RawCMS.Client.dll insert -c test -f /tmp/test.json 
`

where /tmp/test.json are simple json with some data and test are collection where we want to save data.

using RestSharp:
```

string Token="<token>"; 
string ulr = "<url>"; // ie. http://localhost:5000/api/crud/test
string Data = "<data to save in collection>";

RestClient client = new RestClient(url);
RestRequest request = new RestRequest(Method.POST)
{
    //request headers
    RequestFormat = DataFormat.Json
};
request.AddHeader("Content-Type", "application/json");

//add parameters and token to request
request.Parameters.Clear();
request.AddParameter("application/json", Data, ParameterType.RequestBody);
request.AddParameter("Authorization", "Bearer " +Token, ParameterType.HttpHeader);

//make the API request and get a response
IRestResponse response = client.Execute(request);

```
**Expected behavior**
data saved in collection

**Results**
Internal server error.

**Comment by zeppaman** [comment]
maybe related to #37, 401 produces an http error instead of correct status code.

**Comment by zeppaman** [comment]
Using default installation settings
`dotnet RawCMS.Client.dll login -u bob -p XYZ -s http://localhost:28436/ -i raw.client -t raw.secret`
SET RAWCMSCONFIG=C:\Users\d.fontani\Documents\RawCMS.bob.config
dotnet RawCMS.Client.dll insert -c test -f xxx.json`

Saves data.

Can you attach content of json sample? 

Sure to use the correct severl url during login?
