### ISSUE TITLE
Spelling/Grammar Mistakes in ReadMe

### ISSUE THREAD

**Issue by eekbatani** [arduosoft/RawCMS#84]
**Description**
There are several grammar and spelling mistakes in the readMe that compromise the readers experience and comprehension of the information. 

**rReproduction**
Scroll down to readMe content on the repository home page. If the mistakes are not clear, copy and paste them into a word processor such as Microsoft Word, and it will highlight all the spelling and grammar issues. 

**Expected vs Actual behavior**
Some of many examples:
Expected: "Technical Documentation
Actual: "Tecnical Documentation

**Screenshots**

![image](https://user-images.githubusercontent.com/38863472/66084626-1f282080-e53d-11e9-9502-8eac73a28c4f.png)

**Additional context**
I'll proceed to correcting all the spelling and grammar mistakes to enhance the reading experience of the readMe file.

**Comment by zeppaman** [comment]
@eekbatani thank you for the issues and your contribution. PR was accepted and merged.
