### ISSUE TITLE
Review wiki and documentation

### ISSUE THREAD

**Issue by zeppaman** [arduosoft/RawCMS#87]
Documentation needs to be reviewed to remove grammars error and improved to be largely understood.

During this review you should put in user shoes and notes all point that are not clear or section that have to be expanded.

**Comment by varuna-v** [comment]
I'll pick up the documentation :)

**Comment by zeppaman** [comment]
Hi @varuna-v  you are welcome. Please start from develop branch that's the most updated one.

**Comment by zeppaman** [comment]
Hi @varuna-v how is going with documentation? You need some help on this task? For any question you are welcome.

**Comment by hkbiet** [comment]
Any progress on this ? I would like to claim.

**Comment by hkbiet** [comment]
@zeppaman Any progress on this ? I would like to claim it .

**Comment by zeppaman** [comment]
HI @hkbiet as we didn't get any progress, you can pick this. It's also a good way to test our documentation with a person that need to know all the details.

Please mark all question during the read. A new person like you can discover lot of uncovered points that for us that work with it all days are clear.

The documentation consists on many markdown files into /doc folder. You can fork the development branch, work on it and then PR.

For any question just reply to this task.

**Comment by zeppaman** [comment]
@hkbiet thank you for reviewing the documentation. You can join the Gitter channel to keep in touch with the project or claim more tasks. Add a start is also welcome to share the project if you like it.
