### ISSUE TITLE
Related collections inside graphql

### ISSUE THREAD

**Issue by igorvuleta** [arduosoft/RawCMS#94]
Hi there, I have contacted you in regards runtime schema in graphql on gitter. I have seen your example which is pretty cool, but couldn't reporoduce anything like it in SQL, or lets say I could partially, but the problem is that my fields are all of the same type, and that my related tables cannot get loaded, I seen that in mongodb you have a object navigational propertywith which you check if a collection is a navigation property. 

Do you have any advice on how to do it with a sql, or lets say a table relationship?

You can mark this as a question.

**Comment by zeppaman** [comment]
HI Igor,
It's quite hard to give suggestion basing on your description.

On our case there isn't any schema on mongo db, as the mongo db is a NoSQL database. So, what we ask to the user is to create a sort of manifesto where, for each collection, the user tell which fields are into and give info about the type. 

On SQL system there are many way to get this info for free. One solution may be to get this info from EF definition (but this requires  that relation have been mapped before...) or by looking for physical relation like FK that can be read from information schema or using framework like SMO on SQL server.

I hope this may help you.

Anyway, as this question is not related to this project, I will close the issue.
